name: SpeedAV
description: "An Usage Log for Android built with Flutter."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  android_package_manager: ^0.7.0
  mobile_device_identifier: ^0.0.3

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.13
  intl: ^0.20.1
  usage_stats: ^1.2.0
  device_info_plus: ^11.2.1
  dio: ^5.7.0
  http: ^1.3.0
  workmanager: ^0.5.2
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  gap: ^3.0.1
  logger: ^2.5.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  freezed: ^2.5.8

flutter:
  uses-material-design: true

  assets:
    - assets/default-icon.png
    - assets/lock-icon.png
